---
substitutions:
  API_KEY: "HrnLJeueTkAq4x1BBxR2ugB460w9H+Q50uNPBLgnYK0="
  OTA_PASSWORD: "ean1dkAGQi7sz9J3kGM@JG0v2Yohe930"
  PROD_MANIFEST_URL: "https://morganmlg.com/Carb-O-nated/manifest.json"
  BETA_MANIFEST_URL: "https://morganmlg.com/Carb-O-nated/manifest-beta.json"
  WEB_USERNAME: "esphome"
  WEB_PASSWORD: "esphome"
  AP_SSID: "Carb-O-nated"
  AP_PASSWORD: "esphome-fallback"
  DISPLAY_UPDATE_INTERVAL: "200"

esphome:
  name: carb-o-nated
  friendly_name: "Carb-O-nated"
  comment: "ESP32 CO2 Sensor and Display"
  name_add_mac_suffix: true
  project:
    name: "DoYouHost.Carb-O-nated"
    version: "dev"
  includes:
    - co2_levels.h
    - translations.h
    - lookup_tables.h

esp32:
  board: esp32dev
  cpu_frequency: 240MHz
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32_SPIRAM_SUPPORT: n
      # CONFIG_MBEDTLS_DYNAMIC_BUFFER: y
      # CONFIG_MBEDTLS_DYNAMIC_FREE_PEER_CERT: y
      # CONFIG_MBEDTLS_DYNAMIC_FREE_CONFIG_DATA: y
      # CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN: '8192'
      # CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN: '512'
      # CONFIG_MBEDTLS_SSL_PROTO_TLS1_2: y
      # CONFIG_MBEDTLS_TLS_SERVER_AND_CLIENT: y
      # CONFIG_ESP_TASK_WDT_TIMEOUT_S: '60'

dashboard_import:
  package_import_url: github://DoYouHost/Carb-O-nated/esp32-carb-o-nated.yml@main
  import_full_config: false

packages:
  DoYouHost/ESPHomeTemplates:
    url: https://github.com/DoYouHost/ESPHomeTemplates
    files: 
      - basic.yaml
      - debug.yaml
      - updateBetaProdStaging.yaml
      # - webServer3.yaml
      - wifiInfo.yaml
    ref: main
    refresh: 0d
  
  assets: !include assets.yaml

wifi:
  reboot_timeout: 15min
  enable_btm: true
  enable_rrm: true
  post_connect_roaming: true
  ap: 
    ssid: "${AP_SSID}"
    password: "${AP_PASSWORD}"
  on_connect:
    - lambda: |-
        id(improv_component).stop();

time:
  - platform: sntp
    id: sntp_time

captive_portal:

improv_serial:

esp32_improv:
  id: improv_component
  authorizer: button_b

api:
  reboot_timeout: 15min
  encryption:
    key: "${API_KEY}"

  actions:
    - action: set_ambient_pressure
      variables:
        pressure_mbar: int
      then:
        - lambda: "id(co2_sensor)->set_ambient_pressure_compensation(pressure_mbar);"

http_request:
  id: http_request_component
  follow_redirects: true
  verify_ssl: true

ota:
  - platform: esphome
    password: "${OTA_PASSWORD}"
  
  - platform: http_request
    id: !extend ota_http_request
    on_begin:
      - then:
        - logger.log: 
            format: "Starting HTTP Request OTA Update"
            level: INFO
        - component.suspend: main_display
        - component.suspend: co2_sensor

    on_error:
      - then:
        - logger.log: 
            format: "HTTP Request OTA Update Failed"
            level: ERROR
        - component.resume: main_display
        - component.resume: co2_sensor

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: false
  frequency: 400kHz

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

output:
  - platform: ledc
    pin: GPIO4
    id: output_display_backlight

light:
  - platform: monochromatic
    name: "Display Backlight"
    output: output_display_backlight
    restore_mode: RESTORE_DEFAULT_ON

binary_sensor:
  - platform: gpio
    id: button_a
    name: "Button A"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
  
  - platform: gpio
    id: button_b
    name: "Button B"
    pin:
      number: GPIO35
      inverted: true

sensor:
  - platform: scd4x
    address: 0x62
    id: co2_sensor
    update_interval: 15s
    automatic_self_calibration: true
    # temperature_offset: 0
    measurement_mode: single_shot
    co2:
      name: "CO2 Concentration"
      id: scd4x_co2
      unit_of_measurement: "ppm"
      filters:
        - skip_initial: 4
        - exponential_moving_average:
            alpha: 0.1
            send_every: 12
    # temperature:
    #   name: "SCD4x Temperature"
    #   unit_of_measurement: "°C"
    #   filters:
    #     - skip_initial: 4
    #     - exponential_moving_average:
    #         alpha: 0.1
    #         send_every: 12
    # humidity:
    #   name: "SCD4x Humidity"
    #   unit_of_measurement: "%"
    #   filters:
    #     - skip_initial: 4
    #     - exponential_moving_average:
    #         alpha: 0.1
    #         send_every: 12

text_sensor:
  - platform: template
    name: "CO2 Air Quality Level"
    id: co2_level_text
    icon: "mdi:air-filter"
    update_interval: 60s
    lambda: |-
      float co2 = id(scd4x_co2).state;
      CO2Level level = get_co2_level(co2);
      return {get_co2_level_text(level.type)};

select:
  - platform: template
    name: "Dashboard Language"
    id: dashboard_language
    icon: "mdi:translate"
    optimistic: true
    options:
      - "English"
      - "Polski"
      - "Deutsch"
      - "Français"
      - "Español"
    initial_option: "English"
    restore_value: true
    on_value:
      then:
        - lambda: |-
            int lang_map[] = {0, 1, 2, 3, 4};
            if (x == "English") current_language = LANG_EN;
            else if (x == "Polski") current_language = LANG_PL;
            else if (x == "Deutsch") current_language = LANG_DE;
            else if (x == "Français") current_language = LANG_FR;
            else if (x == "Español") current_language = LANG_ES;

font:
  - file: "gfonts://Roboto@700"
    id: roboto_bold_60
    size: 60
    glyphs: "0123456789"
  - file: "gfonts://Roboto@700"
    id: roboto_bold_25
    size: 25
    glyphs: " !\"#$%&'()*+,-./:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~°łéè"
  - file: "gfonts://Roboto@500"
    id: roboto_medium_20
    size: 20
    glyphs: " !\"#$%&'()*+,-./:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~°₀₁₂₃₄₅₆₇₈₉"
  # - file: "gfonts://Roboto"
  #   id: roboto_16b
  #   size: 16
  #   glyphs: " !\"#$%&'()*+,-./:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~°₀₁₂₃₄₅₆₇₈₉0123456789ąćęłńóśźżäöüßàâéèêëîïôùûçáíñĄĆĘŁŃÓŚŹŻÄÖÜÀÂÉÈÊËÎÏÔÙÛÇÁÍÑ"
  # - file: "gfonts://Roboto"
  #   id: roboto_12
  #   size: 12
  #   glyphs: " !\"#$%&'()*+,-./:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~°₀₁₂₃₄₅₆₇₈₉0123456789ąćęłńóśźżäöüßàâéèêëîïôùûçáíñĄĆĘŁŃÓŚŹŻÄÖÜÀÂÉÈÊËÎÏÔÙÛÇÁÍÑ"

display:
  - platform: mipi_spi
    id: main_display
    model: T-DISPLAY
    dc_pin: GPIO16
    cs_pin: GPIO5
    reset_pin: GPIO23
    rotation: 270°
    data_rate: 80MHz
    update_interval: ${DISPLAY_UPDATE_INTERVAL}ms
    lambda: |-
      float co2 = id(scd4x_co2).state;
      
      if (isnan(co2)) {
        it.image(0, 0, id(init_screen));
        int angle = (millis() / 50) % 360;
        for (int i = 0; i < 8; i++) {
          int a = (angle + i * 45) % 360;
          int x = 120 + (int)(25 * cos_lut[a]);
          int y = 67 + (int)(25 * sin_lut[a]);
          it.filled_circle(x, y, 4, Color(100 + i*20, 100 + i*20, 255));
        }
        it.print(120, 100, id(roboto_medium_20), Color(180, 180, 255), TextAlign::TOP_CENTER, get_initializing());
        return;
      }
      
      CO2Level level = get_co2_level(co2);
      Color sc = level.color;
      const char* status_text = get_co2_level_text(level.type);
      static uint8_t frame = 0;
      
      // === BACKGROUND WITH GRADIENT IMAGE ===
      it.image(0, 0, id(bg_gradient));
      
      // === TOP STATUS TEXT ===
      it.print(120, 3, id(roboto_bold_25), sc, TextAlign::TOP_CENTER, status_text);
      
      // === MAIN CO2 VALUE ===
      int depth = frame % 2;
      it.printf(120 - depth, 22, id(roboto_bold_60), sc, 
        TextAlign::TOP_CENTER, "%.0f", co2);
      
      // === SEGMENTED BAR (Dynamic rendering from individual segments) ===
      int max_co2 = 3000;
      float pct = min(1.0f, co2 / max_co2);
      int segments = 18;
      int filled_quarters = (int)((segments * 4) * pct);
      if (filled_quarters > 72) filled_quarters = 72;
      int anim_frame = frame % 4;
      
      int seg_w = 11;
      int seg_gap = 1;
      int bar_x = 7;
      
      // Determine color based on fill level
      const char* color_name;
      if (filled_quarters <= 6) color_name = "green";
      else if (filled_quarters <= 20) color_name = "yellow";
      else if (filled_quarters <= 56) color_name = "orange";
      else color_name = "red";
      
      // Draw all segments
      for (int s = 0; s < segments; s++) {
        int sx = bar_x + s * (seg_w + seg_gap);
        int filled_quarters_for_segment = s * 4;
        
        if (filled_quarters_for_segment + 4 <= filled_quarters) {
          // Segment is fully filled
          if (color_name[0] == 'g') it.image(sx, 97, id(seg_green_3));
          else if (color_name[0] == 'y') it.image(sx, 97, id(seg_yellow_3));
          else if (color_name[0] == 'o') it.image(sx, 97, id(seg_orange_3));
          else it.image(sx, 97, id(seg_red_3));
        } else if (filled_quarters_for_segment < filled_quarters) {
          // Segment is partially filled - select frame based on anim_frame
          if (color_name[0] == 'g') {
            if (anim_frame == 0) it.image(sx, 97, id(seg_green_0));
            else if (anim_frame == 1) it.image(sx, 97, id(seg_green_1));
            else if (anim_frame == 2) it.image(sx, 97, id(seg_green_2));
            else it.image(sx, 97, id(seg_green_3));
          } else if (color_name[0] == 'y') {
            if (anim_frame == 0) it.image(sx, 97, id(seg_yellow_0));
            else if (anim_frame == 1) it.image(sx, 97, id(seg_yellow_1));
            else if (anim_frame == 2) it.image(sx, 97, id(seg_yellow_2));
            else it.image(sx, 97, id(seg_yellow_3));
          } else if (color_name[0] == 'o') {
            if (anim_frame == 0) it.image(sx, 97, id(seg_orange_0));
            else if (anim_frame == 1) it.image(sx, 97, id(seg_orange_1));
            else if (anim_frame == 2) it.image(sx, 97, id(seg_orange_2));
            else it.image(sx, 97, id(seg_orange_3));
          } else {
            if (anim_frame == 0) it.image(sx, 97, id(seg_red_0));
            else if (anim_frame == 1) it.image(sx, 97, id(seg_red_1));
            else if (anim_frame == 2) it.image(sx, 97, id(seg_red_2));
            else it.image(sx, 97, id(seg_red_3));
          }
        } else {
          // Empty segment
          it.image(sx, 97, id(seg_empty));
        }
      }
      

      // === BOTTOM INFO BAR (y: 114-132, safe zone) ===
      // Animated particles near "ppm CO2" text
      int particle_frame = frame % 8;  // 8 frame particle animation
      switch(particle_frame) {
        case 0: it.image(45, 110, id(particles_0)); break;
        case 1: it.image(45, 110, id(particles_1)); break;
        case 2: it.image(45, 110, id(particles_2)); break;
        case 3: it.image(45, 110, id(particles_3)); break;
        case 4: it.image(45, 110, id(particles_4)); break;
        case 5: it.image(45, 110, id(particles_5)); break;
        case 6: it.image(45, 110, id(particles_6)); break;
        case 7: it.image(45, 110, id(particles_7)); break;
      }
      
      it.print(120, 112, id(roboto_medium_20), Color(160, 160, 180), 
        TextAlign::TOP_CENTER, get_unit());
      
      // === CORNER BRACKETS (static, clean) ===
      int corner_len = 8;
      int corner_w = 1;
      // Top-left
      it.filled_rectangle(2, 2, corner_len, corner_w, sc);
      it.filled_rectangle(2, 2, corner_w, corner_len, sc);
      // Top-right
      it.filled_rectangle(240 - corner_len - 2, 2, corner_len, corner_w, sc);
      it.filled_rectangle(237, 2, corner_w, corner_len, sc);
      // Bottom-left
      it.filled_rectangle(2, 132, corner_len, corner_w, sc);
      it.filled_rectangle(2, 124, corner_w, corner_len, sc);
      // Bottom-right
      it.filled_rectangle(240 - corner_len - 2, 132, corner_len, corner_w, sc);
      it.filled_rectangle(237, 124, corner_w, corner_len, sc);

      frame++;
      if(frame >= 8) frame = 0;

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Safe Mode"
  - platform: factory_reset
    name: "Factory Reset"
  - platform: template
    name: "SCD4x Factory Reset"
    entity_category: config
    icon: "mdi:restart-alert"
    on_press:
      - then:
          - logger.log: "Performing SCD4x Factory Reset"
          - scd4x.factory_reset: co2_sensor

status_led:
  pin:
    number: GPIO17
    inverted: false